# Generated by Django 2.2.14 on 2020-07-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('inventory_purchased', models.TextField(blank=True, max_length=400)),
                ('amount', models.CharField(max_length=100)),
                ('balance', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(default='2020-07-29')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('itype', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=20)),
                ('date_added', models.DateField(default='2020-07-29')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'verbose_name': 'Inventory',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('date', models.DateField(default='2020-07-29')),
            ],
        ),
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=100)),
                ('technician', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=100)),
                ('amount_paid', models.CharField(max_length=200)),
                ('balance', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(default='2020-07-29')),
            ],
        ),
    ]
