# Generated by Django 2.2.14 on 2020-07-29 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hard.Customer'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='jobtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hard.JobType'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_status',
            field=models.CharField(choices=[('a', 'Complete'), ('b', 'Incomplete')], max_length=1),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hard.Technician'),
        ),
    ]
