# Generated by Django 2.2.14 on 2020-07-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0003_auto_20200729_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inventory_purchased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hard.Inventory'),
        ),
    ]
