# Generated by Django 2.2.14 on 2020-09-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0004_auto_20200729_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2020-09-03'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_added',
            field=models.DateField(default='2020-09-03'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='date',
            field=models.DateField(default='2020-09-03'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(default='2020-09-03'),
        ),
    ]
