# Generated by Django 2.2.14 on 2020-09-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0005_auto_20200903_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='itype',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='date_added',
        ),
        migrations.AddField(
            model_name='inventory',
            name='calibration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(default='2020-09-03'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='direction_side',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='engine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='holes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='i_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_Type',
            field=models.CharField(blank=True, choices=[('Elements', 'Elements'), ('Nozzles', 'Nozzles'), ('Rotarheads', 'Rotarheads'), ('Valves', 'Valves'), ('Pumps', 'Pumps'), ('Camplates', 'Camplates'), ('Feedpumps', 'Feedpumps'), ('Housings', 'Housings'), ('Switches', 'Switches'), ('Gasket Kit', 'Gasket Kit')], max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='millimeter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='part_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.FloatField(default=8000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='stamping_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='voltage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
