# Generated by Django 2.2.14 on 2020-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0006_auto_20200903_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateField(default='2020-09-03'),
        ),
    ]
