# Generated by Django 2.2.14 on 2020-09-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0007_auto_20200903_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cut',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
