# Generated by Django 2.2.14 on 2020-09-03 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0009_remove_inventory_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 3, 7, 1, 17, 554419, tzinfo=utc)),
        ),
    ]
