# Generated by Django 2.2.14 on 2020-09-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0013_auto_20200903_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, choices=[('Home Store', 'Home Store'), ('Work Store', 'Work Store')], max_length=50),
        ),
    ]
