# Generated by Django 2.2.14 on 2020-09-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0014_auto_20200903_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=100)),
                ('itype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2020-09-07'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='date',
            field=models.DateField(default='2020-09-07'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(default='2020-09-07'),
        ),
    ]
