# Generated by Django 2.2.14 on 2020-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0015_auto_20200907_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='order_status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], max_length=1),
        ),
    ]
