# Generated by Django 2.2.14 on 2020-09-08 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hard', '0017_auto_20200907_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='addedby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2020-09-08'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='date',
            field=models.DateField(default='2020-09-08'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(default='2020-09-08'),
        ),
    ]
