# Generated by Django 2.2.14 on 2020-09-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0021_returnjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2020-09-10'),
        ),
        migrations.AlterField(
            model_name='returnjobs',
            name='datedone',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='technician',
            name='date',
            field=models.DateField(default='2020-09-10'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(default='2020-09-10'),
        ),
    ]
