# Generated by Django 3.1.3 on 2020-12-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard', '0023_auto_20200911_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2020-12-04'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='date',
            field=models.DateField(default='2020-12-04'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(default='2020-12-04'),
        ),
    ]
